<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AListePaysTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        DB::table('a_liste_pays')->delete();
        
        DB::table('a_liste_pays')->insert(array (
            0 => 
            array (
                'id' => 1,
                'code' => 4,
                'alpha2' => 'AF',
                'alpha3' => 'AFG',
                'nom_en_gb' => 'Afghanistan',
                'nom' => 'Afghanistan',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            1 => 
            array (
                'id' => 2,
                'code' => 8,
                'alpha2' => 'AL',
                'alpha3' => 'ALB',
                'nom_en_gb' => 'Albania',
                'nom' => 'Albanie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            2 => 
            array (
                'id' => 3,
                'code' => 10,
                'alpha2' => 'AQ',
                'alpha3' => 'ATA',
                'nom_en_gb' => 'Antarctica',
                'nom' => 'Antarctique',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            3 => 
            array (
                'id' => 4,
                'code' => 12,
                'alpha2' => 'DZ',
                'alpha3' => 'DZA',
                'nom_en_gb' => 'Algeria',
                'nom' => 'Algérie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            4 => 
            array (
                'id' => 5,
                'code' => 16,
                'alpha2' => 'AS',
                'alpha3' => 'ASM',
                'nom_en_gb' => 'American Samoa',
                'nom' => 'Samoa Américaines',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            5 => 
            array (
                'id' => 6,
                'code' => 20,
                'alpha2' => 'AD',
                'alpha3' => 'AND',
                'nom_en_gb' => 'Andorra',
                'nom' => 'Andorre',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            6 => 
            array (
                'id' => 7,
                'code' => 24,
                'alpha2' => 'AO',
                'alpha3' => 'AGO',
                'nom_en_gb' => 'Angola',
                'nom' => 'Angola',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            7 => 
            array (
                'id' => 8,
                'code' => 28,
                'alpha2' => 'AG',
                'alpha3' => 'ATG',
                'nom_en_gb' => 'Antigua and Barbuda',
                'nom' => 'Antigua-et-Barbuda',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            8 => 
            array (
                'id' => 9,
                'code' => 31,
                'alpha2' => 'AZ',
                'alpha3' => 'AZE',
                'nom_en_gb' => 'Azerbaijan',
                'nom' => 'Azerbaïdjan',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            9 => 
            array (
                'id' => 10,
                'code' => 32,
                'alpha2' => 'AR',
                'alpha3' => 'ARG',
                'nom_en_gb' => 'Argentina',
                'nom' => 'Argentine',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            10 => 
            array (
                'id' => 11,
                'code' => 36,
                'alpha2' => 'AU',
                'alpha3' => 'AUS',
                'nom_en_gb' => 'Australia',
                'nom' => 'Australie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            11 => 
            array (
                'id' => 12,
                'code' => 40,
                'alpha2' => 'AT',
                'alpha3' => 'AUT',
                'nom_en_gb' => 'Austria',
                'nom' => 'Autriche',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            12 => 
            array (
                'id' => 13,
                'code' => 44,
                'alpha2' => 'BS',
                'alpha3' => 'BHS',
                'nom_en_gb' => 'Bahamas',
                'nom' => 'Bahamas',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            13 => 
            array (
                'id' => 14,
                'code' => 48,
                'alpha2' => 'BH',
                'alpha3' => 'BHR',
                'nom_en_gb' => 'Bahrain',
                'nom' => 'Bahreïn',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            14 => 
            array (
                'id' => 15,
                'code' => 50,
                'alpha2' => 'BD',
                'alpha3' => 'BGD',
                'nom_en_gb' => 'Bangladesh',
                'nom' => 'Bangladesh',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            15 => 
            array (
                'id' => 16,
                'code' => 51,
                'alpha2' => 'AM',
                'alpha3' => 'ARM',
                'nom_en_gb' => 'Armenia',
                'nom' => 'Arménie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            16 => 
            array (
                'id' => 17,
                'code' => 52,
                'alpha2' => 'BB',
                'alpha3' => 'BRB',
                'nom_en_gb' => 'Barbados',
                'nom' => 'Barbade',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            17 => 
            array (
                'id' => 18,
                'code' => 56,
                'alpha2' => 'BE',
                'alpha3' => 'BEL',
                'nom_en_gb' => 'Belgium',
                'nom' => 'Belgique',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            18 => 
            array (
                'id' => 19,
                'code' => 60,
                'alpha2' => 'BM',
                'alpha3' => 'BMU',
                'nom_en_gb' => 'Bermuda',
                'nom' => 'Bermudes',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            19 => 
            array (
                'id' => 20,
                'code' => 64,
                'alpha2' => 'BT',
                'alpha3' => 'BTN',
                'nom_en_gb' => 'Bhutan',
                'nom' => 'Bhoutan',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            20 => 
            array (
                'id' => 21,
                'code' => 68,
                'alpha2' => 'BO',
                'alpha3' => 'BOL',
                'nom_en_gb' => 'Bolivia',
                'nom' => 'Bolivie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            21 => 
            array (
                'id' => 22,
                'code' => 70,
                'alpha2' => 'BA',
                'alpha3' => 'BIH',
                'nom_en_gb' => 'Bosnia and Herzegovina',
                'nom' => 'Bosnie-Herzégovine',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            22 => 
            array (
                'id' => 23,
                'code' => 72,
                'alpha2' => 'BW',
                'alpha3' => 'BWA',
                'nom_en_gb' => 'Botswana',
                'nom' => 'Botswana',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            23 => 
            array (
                'id' => 24,
                'code' => 74,
                'alpha2' => 'BV',
                'alpha3' => 'BVT',
                'nom_en_gb' => 'Bouvet Island',
                'nom' => 'Île Bouvet',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            24 => 
            array (
                'id' => 25,
                'code' => 76,
                'alpha2' => 'BR',
                'alpha3' => 'BRA',
                'nom_en_gb' => 'Brazil',
                'nom' => 'Brésil',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            25 => 
            array (
                'id' => 26,
                'code' => 84,
                'alpha2' => 'BZ',
                'alpha3' => 'BLZ',
                'nom_en_gb' => 'Belize',
                'nom' => 'Belize',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            26 => 
            array (
                'id' => 27,
                'code' => 86,
                'alpha2' => 'IO',
                'alpha3' => 'IOT',
                'nom_en_gb' => 'British Indian Ocean Territory',
                'nom' => 'Territoire Britannique de l\'Océan Indien',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            27 => 
            array (
                'id' => 28,
                'code' => 90,
                'alpha2' => 'SB',
                'alpha3' => 'SLB',
                'nom_en_gb' => 'Solomon Islands',
                'nom' => 'Îles Salomon',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            28 => 
            array (
                'id' => 29,
                'code' => 92,
                'alpha2' => 'VG',
                'alpha3' => 'VGB',
                'nom_en_gb' => 'British Virgin Islands',
                'nom' => 'Îles Vierges Britanniques',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            29 => 
            array (
                'id' => 30,
                'code' => 96,
                'alpha2' => 'BN',
                'alpha3' => 'BRN',
                'nom_en_gb' => 'Brunei Darussalam',
                'nom' => 'Brunéi Darussalam',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            30 => 
            array (
                'id' => 31,
                'code' => 100,
                'alpha2' => 'BG',
                'alpha3' => 'BGR',
                'nom_en_gb' => 'Bulgaria',
                'nom' => 'Bulgarie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            31 => 
            array (
                'id' => 32,
                'code' => 104,
                'alpha2' => 'MM',
                'alpha3' => 'MMR',
                'nom_en_gb' => 'Myanmar',
                'nom' => 'Myanmar',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            32 => 
            array (
                'id' => 33,
                'code' => 108,
                'alpha2' => 'BI',
                'alpha3' => 'BDI',
                'nom_en_gb' => 'Burundi',
                'nom' => 'Burundi',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            33 => 
            array (
                'id' => 34,
                'code' => 112,
                'alpha2' => 'BY',
                'alpha3' => 'BLR',
                'nom_en_gb' => 'Belarus',
                'nom' => 'Biélorussie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            34 => 
            array (
                'id' => 35,
                'code' => 116,
                'alpha2' => 'KH',
                'alpha3' => 'KHM',
                'nom_en_gb' => 'Cambodia',
                'nom' => 'Cambodge',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            35 => 
            array (
                'id' => 36,
                'code' => 120,
                'alpha2' => 'CM',
                'alpha3' => 'CMR',
                'nom_en_gb' => 'Cameroon',
                'nom' => 'Cameroun',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            36 => 
            array (
                'id' => 37,
                'code' => 124,
                'alpha2' => 'CA',
                'alpha3' => 'CAN',
                'nom_en_gb' => 'Canada',
                'nom' => 'Canada',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            37 => 
            array (
                'id' => 38,
                'code' => 132,
                'alpha2' => 'CV',
                'alpha3' => 'CPV',
                'nom_en_gb' => 'Cape Verde',
                'nom' => 'Cap-vert',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            38 => 
            array (
                'id' => 39,
                'code' => 136,
                'alpha2' => 'KY',
                'alpha3' => 'CYM',
                'nom_en_gb' => 'Cayman Islands',
                'nom' => 'Îles Caïmanes',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            39 => 
            array (
                'id' => 40,
                'code' => 140,
                'alpha2' => 'CF',
                'alpha3' => 'CAF',
                'nom_en_gb' => 'Central African',
                'nom' => 'République Centrafricaine',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            40 => 
            array (
                'id' => 41,
                'code' => 144,
                'alpha2' => 'LK',
                'alpha3' => 'LKA',
                'nom_en_gb' => 'Sri Lanka',
                'nom' => 'Sri Lanka',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            41 => 
            array (
                'id' => 42,
                'code' => 148,
                'alpha2' => 'TD',
                'alpha3' => 'TCD',
                'nom_en_gb' => 'Chad',
                'nom' => 'Tchad',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            42 => 
            array (
                'id' => 43,
                'code' => 152,
                'alpha2' => 'CL',
                'alpha3' => 'CHL',
                'nom_en_gb' => 'Chile',
                'nom' => 'Chili',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            43 => 
            array (
                'id' => 44,
                'code' => 156,
                'alpha2' => 'CN',
                'alpha3' => 'CHN',
                'nom_en_gb' => 'China',
                'nom' => 'Chine',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            44 => 
            array (
                'id' => 45,
                'code' => 158,
                'alpha2' => 'TW',
                'alpha3' => 'TWN',
                'nom_en_gb' => 'Taiwan',
                'nom' => 'Taïwan',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            45 => 
            array (
                'id' => 46,
                'code' => 162,
                'alpha2' => 'CX',
                'alpha3' => 'CXR',
                'nom_en_gb' => 'Christmas Island',
                'nom' => 'Île Christmas',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            46 => 
            array (
                'id' => 47,
                'code' => 166,
                'alpha2' => 'CC',
                'alpha3' => 'CCK',
            'nom_en_gb' => 'Cocos (Keeling) Islands',
            'nom' => 'Îles Cocos (Keeling)',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            47 => 
            array (
                'id' => 48,
                'code' => 170,
                'alpha2' => 'CO',
                'alpha3' => 'COL',
                'nom_en_gb' => 'Colombia',
                'nom' => 'Colombie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            48 => 
            array (
                'id' => 49,
                'code' => 174,
                'alpha2' => 'KM',
                'alpha3' => 'COM',
                'nom_en_gb' => 'Comoros',
                'nom' => 'Comores',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            49 => 
            array (
                'id' => 50,
                'code' => 175,
                'alpha2' => 'YT',
                'alpha3' => 'MYT',
                'nom_en_gb' => 'Mayotte',
                'nom' => 'Mayotte',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            50 => 
            array (
                'id' => 51,
                'code' => 178,
                'alpha2' => 'CG',
                'alpha3' => 'COG',
                'nom_en_gb' => 'Republic of the Congo',
                'nom' => 'République du Congo',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            51 => 
            array (
                'id' => 52,
                'code' => 180,
                'alpha2' => 'CD',
                'alpha3' => 'COD',
                'nom_en_gb' => 'The Democratic Republic Of The Congo',
                'nom' => 'République Démocratique du Congo',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            52 => 
            array (
                'id' => 53,
                'code' => 184,
                'alpha2' => 'CK',
                'alpha3' => 'COK',
                'nom_en_gb' => 'Cook Islands',
                'nom' => 'Îles Cook',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            53 => 
            array (
                'id' => 54,
                'code' => 188,
                'alpha2' => 'CR',
                'alpha3' => 'CRI',
                'nom_en_gb' => 'Costa Rica',
                'nom' => 'Costa Rica',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            54 => 
            array (
                'id' => 55,
                'code' => 191,
                'alpha2' => 'HR',
                'alpha3' => 'HRV',
                'nom_en_gb' => 'Croatia',
                'nom' => 'Croatie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            55 => 
            array (
                'id' => 56,
                'code' => 192,
                'alpha2' => 'CU',
                'alpha3' => 'CUB',
                'nom_en_gb' => 'Cuba',
                'nom' => 'Cuba',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            56 => 
            array (
                'id' => 57,
                'code' => 196,
                'alpha2' => 'CY',
                'alpha3' => 'CYP',
                'nom_en_gb' => 'Cyprus',
                'nom' => 'Chypre',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            57 => 
            array (
                'id' => 58,
                'code' => 203,
                'alpha2' => 'CZ',
                'alpha3' => 'CZE',
                'nom_en_gb' => 'Czech Republic',
                'nom' => 'République Tchèque',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            58 => 
            array (
                'id' => 59,
                'code' => 204,
                'alpha2' => 'BJ',
                'alpha3' => 'BEN',
                'nom_en_gb' => 'Benin',
                'nom' => 'Bénin',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            59 => 
            array (
                'id' => 60,
                'code' => 208,
                'alpha2' => 'DK',
                'alpha3' => 'DNK',
                'nom_en_gb' => 'Denmark',
                'nom' => 'Danemark',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            60 => 
            array (
                'id' => 61,
                'code' => 212,
                'alpha2' => 'DM',
                'alpha3' => 'DMA',
                'nom_en_gb' => 'Dominica',
                'nom' => 'Dominique',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            61 => 
            array (
                'id' => 62,
                'code' => 214,
                'alpha2' => 'DO',
                'alpha3' => 'DOM',
                'nom_en_gb' => 'Dominican Republic',
                'nom' => 'République Dominicaine',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            62 => 
            array (
                'id' => 63,
                'code' => 218,
                'alpha2' => 'EC',
                'alpha3' => 'ECU',
                'nom_en_gb' => 'Ecuador',
                'nom' => 'Équateur',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            63 => 
            array (
                'id' => 64,
                'code' => 222,
                'alpha2' => 'SV',
                'alpha3' => 'SLV',
                'nom_en_gb' => 'El Salvador',
                'nom' => 'El Salvador',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            64 => 
            array (
                'id' => 65,
                'code' => 226,
                'alpha2' => 'GQ',
                'alpha3' => 'GNQ',
                'nom_en_gb' => 'Equatorial Guinea',
                'nom' => 'Guinée Équatoriale',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            65 => 
            array (
                'id' => 66,
                'code' => 231,
                'alpha2' => 'ET',
                'alpha3' => 'ETH',
                'nom_en_gb' => 'Ethiopia',
                'nom' => 'Éthiopie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            66 => 
            array (
                'id' => 67,
                'code' => 232,
                'alpha2' => 'ER',
                'alpha3' => 'ERI',
                'nom_en_gb' => 'Eritrea',
                'nom' => 'Érythrée',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            67 => 
            array (
                'id' => 68,
                'code' => 233,
                'alpha2' => 'EE',
                'alpha3' => 'EST',
                'nom_en_gb' => 'Estonia',
                'nom' => 'Estonie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            68 => 
            array (
                'id' => 69,
                'code' => 234,
                'alpha2' => 'FO',
                'alpha3' => 'FRO',
                'nom_en_gb' => 'Faroe Islands',
                'nom' => 'Îles Féroé',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            69 => 
            array (
                'id' => 70,
                'code' => 238,
                'alpha2' => 'FK',
                'alpha3' => 'FLK',
                'nom_en_gb' => 'Falkland Islands',
            'nom' => 'Îles (malvinas) Falkland',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            70 => 
            array (
                'id' => 71,
                'code' => 239,
                'alpha2' => 'GS',
                'alpha3' => 'SGS',
                'nom_en_gb' => 'South Georgia and the South Sandwich Islands',
                'nom' => 'Géorgie du Sud et les Îles Sandwich du Sud',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            71 => 
            array (
                'id' => 72,
                'code' => 242,
                'alpha2' => 'FJ',
                'alpha3' => 'FJI',
                'nom_en_gb' => 'Fiji',
                'nom' => 'Fidji',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            72 => 
            array (
                'id' => 73,
                'code' => 246,
                'alpha2' => 'FI',
                'alpha3' => 'FIN',
                'nom_en_gb' => 'Finland',
                'nom' => 'Finlande',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            73 => 
            array (
                'id' => 74,
                'code' => 248,
                'alpha2' => 'AX',
                'alpha3' => 'ALA',
                'nom_en_gb' => 'Åland Islands',
                'nom' => 'Îles Åland',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            74 => 
            array (
                'id' => 75,
                'code' => 250,
                'alpha2' => 'FR',
                'alpha3' => 'FRA',
                'nom_en_gb' => 'France',
                'nom' => 'France',
                'defaut' => 1,
                'tva' => 1,
                'taux_tva' => '20.00',
            ),
            75 => 
            array (
                'id' => 76,
                'code' => 254,
                'alpha2' => 'GF',
                'alpha3' => 'GUF',
                'nom_en_gb' => 'French Guiana',
                'nom' => 'Guyane Française',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            76 => 
            array (
                'id' => 77,
                'code' => 258,
                'alpha2' => 'PF',
                'alpha3' => 'PYF',
                'nom_en_gb' => 'French Polynesia',
                'nom' => 'Polynésie Française',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            77 => 
            array (
                'id' => 78,
                'code' => 260,
                'alpha2' => 'TF',
                'alpha3' => 'ATF',
                'nom_en_gb' => 'French Southern Territories',
                'nom' => 'Terres Australes Françaises',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            78 => 
            array (
                'id' => 79,
                'code' => 262,
                'alpha2' => 'DJ',
                'alpha3' => 'DJI',
                'nom_en_gb' => 'Djibouti',
                'nom' => 'Djibouti',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            79 => 
            array (
                'id' => 80,
                'code' => 266,
                'alpha2' => 'GA',
                'alpha3' => 'GAB',
                'nom_en_gb' => 'Gabon',
                'nom' => 'Gabon',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            80 => 
            array (
                'id' => 81,
                'code' => 268,
                'alpha2' => 'GE',
                'alpha3' => 'GEO',
                'nom_en_gb' => 'Georgia',
                'nom' => 'Géorgie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            81 => 
            array (
                'id' => 82,
                'code' => 270,
                'alpha2' => 'GM',
                'alpha3' => 'GMB',
                'nom_en_gb' => 'Gambia',
                'nom' => 'Gambie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            82 => 
            array (
                'id' => 83,
                'code' => 275,
                'alpha2' => 'PS',
                'alpha3' => 'PSE',
                'nom_en_gb' => 'Occupied Palestinian Territory',
                'nom' => 'Territoire Palestinien Occupé',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            83 => 
            array (
                'id' => 84,
                'code' => 276,
                'alpha2' => 'DE',
                'alpha3' => 'DEU',
                'nom_en_gb' => 'Germany',
                'nom' => 'Allemagne',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            84 => 
            array (
                'id' => 85,
                'code' => 288,
                'alpha2' => 'GH',
                'alpha3' => 'GHA',
                'nom_en_gb' => 'Ghana',
                'nom' => 'Ghana',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            85 => 
            array (
                'id' => 86,
                'code' => 292,
                'alpha2' => 'GI',
                'alpha3' => 'GIB',
                'nom_en_gb' => 'Gibraltar',
                'nom' => 'Gibraltar',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            86 => 
            array (
                'id' => 87,
                'code' => 296,
                'alpha2' => 'KI',
                'alpha3' => 'KIR',
                'nom_en_gb' => 'Kiribati',
                'nom' => 'Kiribati',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            87 => 
            array (
                'id' => 88,
                'code' => 300,
                'alpha2' => 'GR',
                'alpha3' => 'GRC',
                'nom_en_gb' => 'Greece',
                'nom' => 'Grèce',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            88 => 
            array (
                'id' => 89,
                'code' => 304,
                'alpha2' => 'GL',
                'alpha3' => 'GRL',
                'nom_en_gb' => 'Greenland',
                'nom' => 'Groenland',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            89 => 
            array (
                'id' => 90,
                'code' => 308,
                'alpha2' => 'GD',
                'alpha3' => 'GRD',
                'nom_en_gb' => 'Grenada',
                'nom' => 'Grenade',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            90 => 
            array (
                'id' => 91,
                'code' => 312,
                'alpha2' => 'GP',
                'alpha3' => 'GLP',
                'nom_en_gb' => 'Guadeloupe',
                'nom' => 'Guadeloupe',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            91 => 
            array (
                'id' => 92,
                'code' => 316,
                'alpha2' => 'GU',
                'alpha3' => 'GUM',
                'nom_en_gb' => 'Guam',
                'nom' => 'Guam',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            92 => 
            array (
                'id' => 93,
                'code' => 320,
                'alpha2' => 'GT',
                'alpha3' => 'GTM',
                'nom_en_gb' => 'Guatemala',
                'nom' => 'Guatemala',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            93 => 
            array (
                'id' => 94,
                'code' => 324,
                'alpha2' => 'GN',
                'alpha3' => 'GIN',
                'nom_en_gb' => 'Guinea',
                'nom' => 'Guinée',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            94 => 
            array (
                'id' => 95,
                'code' => 328,
                'alpha2' => 'GY',
                'alpha3' => 'GUY',
                'nom_en_gb' => 'Guyana',
                'nom' => 'Guyana',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            95 => 
            array (
                'id' => 96,
                'code' => 332,
                'alpha2' => 'HT',
                'alpha3' => 'HTI',
                'nom_en_gb' => 'Haiti',
                'nom' => 'Haïti',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            96 => 
            array (
                'id' => 97,
                'code' => 334,
                'alpha2' => 'HM',
                'alpha3' => 'HMD',
                'nom_en_gb' => 'Heard Island and McDonald Islands',
                'nom' => 'Îles Heard et Mcdonald',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            97 => 
            array (
                'id' => 98,
                'code' => 336,
                'alpha2' => 'VA',
                'alpha3' => 'VAT',
                'nom_en_gb' => 'Vatican City State',
            'nom' => 'Saint-Siège (état de la Cité du Vatican)',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            98 => 
            array (
                'id' => 99,
                'code' => 340,
                'alpha2' => 'HN',
                'alpha3' => 'HND',
                'nom_en_gb' => 'Honduras',
                'nom' => 'Honduras',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            99 => 
            array (
                'id' => 100,
                'code' => 344,
                'alpha2' => 'HK',
                'alpha3' => 'HKG',
                'nom_en_gb' => 'Hong Kong',
                'nom' => 'Hong-Kong',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            100 => 
            array (
                'id' => 101,
                'code' => 348,
                'alpha2' => 'HU',
                'alpha3' => 'HUN',
                'nom_en_gb' => 'Hungary',
                'nom' => 'Hongrie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            101 => 
            array (
                'id' => 102,
                'code' => 352,
                'alpha2' => 'IS',
                'alpha3' => 'ISL',
                'nom_en_gb' => 'Iceland',
                'nom' => 'Islande',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            102 => 
            array (
                'id' => 103,
                'code' => 356,
                'alpha2' => 'IN',
                'alpha3' => 'IND',
                'nom_en_gb' => 'India',
                'nom' => 'Inde',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            103 => 
            array (
                'id' => 104,
                'code' => 360,
                'alpha2' => 'ID',
                'alpha3' => 'IDN',
                'nom_en_gb' => 'Indonesia',
                'nom' => 'Indonésie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            104 => 
            array (
                'id' => 105,
                'code' => 364,
                'alpha2' => 'IR',
                'alpha3' => 'IRN',
                'nom_en_gb' => 'Islamic Republic of Iran',
                'nom' => 'République Islamique d\'Iran',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            105 => 
            array (
                'id' => 106,
                'code' => 368,
                'alpha2' => 'IQ',
                'alpha3' => 'IRQ',
                'nom_en_gb' => 'Iraq',
                'nom' => 'Iraq',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            106 => 
            array (
                'id' => 107,
                'code' => 372,
                'alpha2' => 'IE',
                'alpha3' => 'IRL',
                'nom_en_gb' => 'Ireland',
                'nom' => 'Irlande',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            107 => 
            array (
                'id' => 108,
                'code' => 376,
                'alpha2' => 'IL',
                'alpha3' => 'ISR',
                'nom_en_gb' => 'Israel',
                'nom' => 'Israël',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            108 => 
            array (
                'id' => 109,
                'code' => 380,
                'alpha2' => 'IT',
                'alpha3' => 'ITA',
                'nom_en_gb' => 'Italy',
                'nom' => 'Italie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            109 => 
            array (
                'id' => 110,
                'code' => 384,
                'alpha2' => 'CI',
                'alpha3' => 'CIV',
                'nom_en_gb' => 'Côte d\'Ivoire',
                'nom' => 'Côte d\'Ivoire',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            110 => 
            array (
                'id' => 111,
                'code' => 388,
                'alpha2' => 'JM',
                'alpha3' => 'JAM',
                'nom_en_gb' => 'Jamaica',
                'nom' => 'Jamaïque',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            111 => 
            array (
                'id' => 112,
                'code' => 392,
                'alpha2' => 'JP',
                'alpha3' => 'JPN',
                'nom_en_gb' => 'Japan',
                'nom' => 'Japon',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            112 => 
            array (
                'id' => 113,
                'code' => 398,
                'alpha2' => 'KZ',
                'alpha3' => 'KAZ',
                'nom_en_gb' => 'Kazakhstan',
                'nom' => 'Kazakhstan',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            113 => 
            array (
                'id' => 114,
                'code' => 400,
                'alpha2' => 'JO',
                'alpha3' => 'JOR',
                'nom_en_gb' => 'Jordan',
                'nom' => 'Jordanie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            114 => 
            array (
                'id' => 115,
                'code' => 404,
                'alpha2' => 'KE',
                'alpha3' => 'KEN',
                'nom_en_gb' => 'Kenya',
                'nom' => 'Kenya',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            115 => 
            array (
                'id' => 116,
                'code' => 408,
                'alpha2' => 'KP',
                'alpha3' => 'PRK',
                'nom_en_gb' => 'Democratic People\'s Republic of Korea',
                'nom' => 'République Populaire Démocratique de Corée',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            116 => 
            array (
                'id' => 117,
                'code' => 410,
                'alpha2' => 'KR',
                'alpha3' => 'KOR',
                'nom_en_gb' => 'Republic of Korea',
                'nom' => 'République de Corée',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            117 => 
            array (
                'id' => 118,
                'code' => 414,
                'alpha2' => 'KW',
                'alpha3' => 'KWT',
                'nom_en_gb' => 'Kuwait',
                'nom' => 'Koweït',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            118 => 
            array (
                'id' => 119,
                'code' => 417,
                'alpha2' => 'KG',
                'alpha3' => 'KGZ',
                'nom_en_gb' => 'Kyrgyzstan',
                'nom' => 'Kirghizistan',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            119 => 
            array (
                'id' => 120,
                'code' => 418,
                'alpha2' => 'LA',
                'alpha3' => 'LAO',
                'nom_en_gb' => 'Lao People\'s Democratic Republic',
                'nom' => 'République Démocratique Populaire Lao',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            120 => 
            array (
                'id' => 121,
                'code' => 422,
                'alpha2' => 'LB',
                'alpha3' => 'LBN',
                'nom_en_gb' => 'Lebanon',
                'nom' => 'Liban',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            121 => 
            array (
                'id' => 122,
                'code' => 426,
                'alpha2' => 'LS',
                'alpha3' => 'LSO',
                'nom_en_gb' => 'Lesotho',
                'nom' => 'Lesotho',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            122 => 
            array (
                'id' => 123,
                'code' => 428,
                'alpha2' => 'LV',
                'alpha3' => 'LVA',
                'nom_en_gb' => 'Latvia',
                'nom' => 'Lettonie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            123 => 
            array (
                'id' => 124,
                'code' => 430,
                'alpha2' => 'LR',
                'alpha3' => 'LBR',
                'nom_en_gb' => 'Liberia',
                'nom' => 'Libéria',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            124 => 
            array (
                'id' => 125,
                'code' => 434,
                'alpha2' => 'LY',
                'alpha3' => 'LBY',
                'nom_en_gb' => 'Libyan Arab Jamahiriya',
                'nom' => 'Jamahiriya Arabe Libyenne',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            125 => 
            array (
                'id' => 126,
                'code' => 438,
                'alpha2' => 'LI',
                'alpha3' => 'LIE',
                'nom_en_gb' => 'Liechtenstein',
                'nom' => 'Liechtenstein',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            126 => 
            array (
                'id' => 127,
                'code' => 440,
                'alpha2' => 'LT',
                'alpha3' => 'LTU',
                'nom_en_gb' => 'Lithuania',
                'nom' => 'Lituanie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            127 => 
            array (
                'id' => 128,
                'code' => 442,
                'alpha2' => 'LU',
                'alpha3' => 'LUX',
                'nom_en_gb' => 'Luxembourg',
                'nom' => 'Luxembourg',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            128 => 
            array (
                'id' => 129,
                'code' => 446,
                'alpha2' => 'MO',
                'alpha3' => 'MAC',
                'nom_en_gb' => 'Macao',
                'nom' => 'Macao',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            129 => 
            array (
                'id' => 130,
                'code' => 450,
                'alpha2' => 'MG',
                'alpha3' => 'MDG',
                'nom_en_gb' => 'Madagascar',
                'nom' => 'Madagascar',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            130 => 
            array (
                'id' => 131,
                'code' => 454,
                'alpha2' => 'MW',
                'alpha3' => 'MWI',
                'nom_en_gb' => 'Malawi',
                'nom' => 'Malawi',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            131 => 
            array (
                'id' => 132,
                'code' => 458,
                'alpha2' => 'MY',
                'alpha3' => 'MYS',
                'nom_en_gb' => 'Malaysia',
                'nom' => 'Malaisie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            132 => 
            array (
                'id' => 133,
                'code' => 462,
                'alpha2' => 'MV',
                'alpha3' => 'MDV',
                'nom_en_gb' => 'Maldives',
                'nom' => 'Maldives',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            133 => 
            array (
                'id' => 134,
                'code' => 466,
                'alpha2' => 'ML',
                'alpha3' => 'MLI',
                'nom_en_gb' => 'Mali',
                'nom' => 'Mali',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            134 => 
            array (
                'id' => 135,
                'code' => 470,
                'alpha2' => 'MT',
                'alpha3' => 'MLT',
                'nom_en_gb' => 'Malta',
                'nom' => 'Malte',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            135 => 
            array (
                'id' => 136,
                'code' => 474,
                'alpha2' => 'MQ',
                'alpha3' => 'MTQ',
                'nom_en_gb' => 'Martinique',
                'nom' => 'Martinique',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            136 => 
            array (
                'id' => 137,
                'code' => 478,
                'alpha2' => 'MR',
                'alpha3' => 'MRT',
                'nom_en_gb' => 'Mauritania',
                'nom' => 'Mauritanie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            137 => 
            array (
                'id' => 138,
                'code' => 480,
                'alpha2' => 'MU',
                'alpha3' => 'MUS',
                'nom_en_gb' => 'Mauritius',
                'nom' => 'Maurice',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            138 => 
            array (
                'id' => 139,
                'code' => 484,
                'alpha2' => 'MX',
                'alpha3' => 'MEX',
                'nom_en_gb' => 'Mexico',
                'nom' => 'Mexique',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            139 => 
            array (
                'id' => 140,
                'code' => 492,
                'alpha2' => 'MC',
                'alpha3' => 'MCO',
                'nom_en_gb' => 'Monaco',
                'nom' => 'Monaco',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            140 => 
            array (
                'id' => 141,
                'code' => 496,
                'alpha2' => 'MN',
                'alpha3' => 'MNG',
                'nom_en_gb' => 'Mongolia',
                'nom' => 'Mongolie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            141 => 
            array (
                'id' => 142,
                'code' => 498,
                'alpha2' => 'MD',
                'alpha3' => 'MDA',
                'nom_en_gb' => 'Republic of Moldova',
                'nom' => 'République de Moldova',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            142 => 
            array (
                'id' => 143,
                'code' => 500,
                'alpha2' => 'MS',
                'alpha3' => 'MSR',
                'nom_en_gb' => 'Montserrat',
                'nom' => 'Montserrat',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            143 => 
            array (
                'id' => 144,
                'code' => 504,
                'alpha2' => 'MA',
                'alpha3' => 'MAR',
                'nom_en_gb' => 'Morocco',
                'nom' => 'Maroc',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            144 => 
            array (
                'id' => 145,
                'code' => 508,
                'alpha2' => 'MZ',
                'alpha3' => 'MOZ',
                'nom_en_gb' => 'Mozambique',
                'nom' => 'Mozambique',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            145 => 
            array (
                'id' => 146,
                'code' => 512,
                'alpha2' => 'OM',
                'alpha3' => 'OMN',
                'nom_en_gb' => 'Oman',
                'nom' => 'Oman',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            146 => 
            array (
                'id' => 147,
                'code' => 516,
                'alpha2' => 'NA',
                'alpha3' => 'NAM',
                'nom_en_gb' => 'Namibia',
                'nom' => 'Namibie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            147 => 
            array (
                'id' => 148,
                'code' => 520,
                'alpha2' => 'NR',
                'alpha3' => 'NRU',
                'nom_en_gb' => 'Nauru',
                'nom' => 'Nauru',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            148 => 
            array (
                'id' => 149,
                'code' => 524,
                'alpha2' => 'NP',
                'alpha3' => 'NPL',
                'nom_en_gb' => 'Nepal',
                'nom' => 'Népal',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            149 => 
            array (
                'id' => 150,
                'code' => 528,
                'alpha2' => 'NL',
                'alpha3' => 'NLD',
                'nom_en_gb' => 'Netherlands',
                'nom' => 'Pays-Bas',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            150 => 
            array (
                'id' => 151,
                'code' => 530,
                'alpha2' => 'AN',
                'alpha3' => 'ANT',
                'nom_en_gb' => 'Netherlands Antilles',
                'nom' => 'Antilles Néerlandaises',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            151 => 
            array (
                'id' => 152,
                'code' => 533,
                'alpha2' => 'AW',
                'alpha3' => 'ABW',
                'nom_en_gb' => 'Aruba',
                'nom' => 'Aruba',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            152 => 
            array (
                'id' => 153,
                'code' => 540,
                'alpha2' => 'NC',
                'alpha3' => 'NCL',
                'nom_en_gb' => 'New Caledonia',
                'nom' => 'Nouvelle-Calédonie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            153 => 
            array (
                'id' => 154,
                'code' => 548,
                'alpha2' => 'VU',
                'alpha3' => 'VUT',
                'nom_en_gb' => 'Vanuatu',
                'nom' => 'Vanuatu',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            154 => 
            array (
                'id' => 155,
                'code' => 554,
                'alpha2' => 'NZ',
                'alpha3' => 'NZL',
                'nom_en_gb' => 'New Zealand',
                'nom' => 'Nouvelle-Zélande',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            155 => 
            array (
                'id' => 156,
                'code' => 558,
                'alpha2' => 'NI',
                'alpha3' => 'NIC',
                'nom_en_gb' => 'Nicaragua',
                'nom' => 'Nicaragua',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            156 => 
            array (
                'id' => 157,
                'code' => 562,
                'alpha2' => 'NE',
                'alpha3' => 'NER',
                'nom_en_gb' => 'Niger',
                'nom' => 'Niger',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            157 => 
            array (
                'id' => 158,
                'code' => 566,
                'alpha2' => 'NG',
                'alpha3' => 'NGA',
                'nom_en_gb' => 'Nigeria',
                'nom' => 'Nigéria',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            158 => 
            array (
                'id' => 159,
                'code' => 570,
                'alpha2' => 'NU',
                'alpha3' => 'NIU',
                'nom_en_gb' => 'Niue',
                'nom' => 'Niué',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            159 => 
            array (
                'id' => 160,
                'code' => 574,
                'alpha2' => 'NF',
                'alpha3' => 'NFK',
                'nom_en_gb' => 'Norfolk Island',
                'nom' => 'Île Norfolk',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            160 => 
            array (
                'id' => 161,
                'code' => 578,
                'alpha2' => 'NO',
                'alpha3' => 'NOR',
                'nom_en_gb' => 'Norway',
                'nom' => 'Norvège',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            161 => 
            array (
                'id' => 162,
                'code' => 580,
                'alpha2' => 'MP',
                'alpha3' => 'MNP',
                'nom_en_gb' => 'Northern Mariana Islands',
                'nom' => 'Îles Mariannes du Nord',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            162 => 
            array (
                'id' => 163,
                'code' => 581,
                'alpha2' => 'UM',
                'alpha3' => 'UMI',
                'nom_en_gb' => 'United States Minor Outlying Islands',
                'nom' => 'Îles Mineures Éloignées des États-Unis',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            163 => 
            array (
                'id' => 164,
                'code' => 583,
                'alpha2' => 'FM',
                'alpha3' => 'FSM',
                'nom_en_gb' => 'Federated States of Micronesia',
                'nom' => 'États Fédérés de Micronésie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            164 => 
            array (
                'id' => 165,
                'code' => 584,
                'alpha2' => 'MH',
                'alpha3' => 'MHL',
                'nom_en_gb' => 'Marshall Islands',
                'nom' => 'Îles Marshall',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            165 => 
            array (
                'id' => 166,
                'code' => 585,
                'alpha2' => 'PW',
                'alpha3' => 'PLW',
                'nom_en_gb' => 'Palau',
                'nom' => 'Palaos',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            166 => 
            array (
                'id' => 167,
                'code' => 586,
                'alpha2' => 'PK',
                'alpha3' => 'PAK',
                'nom_en_gb' => 'Pakistan',
                'nom' => 'Pakistan',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            167 => 
            array (
                'id' => 168,
                'code' => 591,
                'alpha2' => 'PA',
                'alpha3' => 'PAN',
                'nom_en_gb' => 'Panama',
                'nom' => 'Panama',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            168 => 
            array (
                'id' => 169,
                'code' => 598,
                'alpha2' => 'PG',
                'alpha3' => 'PNG',
                'nom_en_gb' => 'Papua New Guinea',
                'nom' => 'Papouasie-Nouvelle-Guinée',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            169 => 
            array (
                'id' => 170,
                'code' => 600,
                'alpha2' => 'PY',
                'alpha3' => 'PRY',
                'nom_en_gb' => 'Paraguay',
                'nom' => 'Paraguay',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            170 => 
            array (
                'id' => 171,
                'code' => 604,
                'alpha2' => 'PE',
                'alpha3' => 'PER',
                'nom_en_gb' => 'Peru',
                'nom' => 'Pérou',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            171 => 
            array (
                'id' => 172,
                'code' => 608,
                'alpha2' => 'PH',
                'alpha3' => 'PHL',
                'nom_en_gb' => 'Philippines',
                'nom' => 'Philippines',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            172 => 
            array (
                'id' => 173,
                'code' => 612,
                'alpha2' => 'PN',
                'alpha3' => 'PCN',
                'nom_en_gb' => 'Pitcairn',
                'nom' => 'Pitcairn',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            173 => 
            array (
                'id' => 174,
                'code' => 616,
                'alpha2' => 'PL',
                'alpha3' => 'POL',
                'nom_en_gb' => 'Poland',
                'nom' => 'Pologne',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            174 => 
            array (
                'id' => 175,
                'code' => 620,
                'alpha2' => 'PT',
                'alpha3' => 'PRT',
                'nom_en_gb' => 'Portugal',
                'nom' => 'Portugal',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            175 => 
            array (
                'id' => 176,
                'code' => 624,
                'alpha2' => 'GW',
                'alpha3' => 'GNB',
                'nom_en_gb' => 'Guinea-Bissau',
                'nom' => 'Guinée-Bissau',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            176 => 
            array (
                'id' => 177,
                'code' => 626,
                'alpha2' => 'TL',
                'alpha3' => 'TLS',
                'nom_en_gb' => 'Timor-Leste',
                'nom' => 'Timor-Leste',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            177 => 
            array (
                'id' => 178,
                'code' => 630,
                'alpha2' => 'PR',
                'alpha3' => 'PRI',
                'nom_en_gb' => 'Puerto Rico',
                'nom' => 'Porto Rico',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            178 => 
            array (
                'id' => 179,
                'code' => 634,
                'alpha2' => 'QA',
                'alpha3' => 'QAT',
                'nom_en_gb' => 'Qatar',
                'nom' => 'Qatar',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            179 => 
            array (
                'id' => 180,
                'code' => 638,
                'alpha2' => 'RE',
                'alpha3' => 'REU',
                'nom_en_gb' => 'Réunion',
                'nom' => 'Réunion',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            180 => 
            array (
                'id' => 181,
                'code' => 642,
                'alpha2' => 'RO',
                'alpha3' => 'ROU',
                'nom_en_gb' => 'Romania',
                'nom' => 'Roumanie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            181 => 
            array (
                'id' => 182,
                'code' => 643,
                'alpha2' => 'RU',
                'alpha3' => 'RUS',
                'nom_en_gb' => 'Russian Federation',
                'nom' => 'Fédération de Russie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            182 => 
            array (
                'id' => 183,
                'code' => 646,
                'alpha2' => 'RW',
                'alpha3' => 'RWA',
                'nom_en_gb' => 'Rwanda',
                'nom' => 'Rwanda',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            183 => 
            array (
                'id' => 184,
                'code' => 654,
                'alpha2' => 'SH',
                'alpha3' => 'SHN',
                'nom_en_gb' => 'Saint Helena',
                'nom' => 'Sainte-Hélène',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            184 => 
            array (
                'id' => 185,
                'code' => 659,
                'alpha2' => 'KN',
                'alpha3' => 'KNA',
                'nom_en_gb' => 'Saint Kitts and Nevis',
                'nom' => 'Saint-Kitts-et-Nevis',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            185 => 
            array (
                'id' => 186,
                'code' => 660,
                'alpha2' => 'AI',
                'alpha3' => 'AIA',
                'nom_en_gb' => 'Anguilla',
                'nom' => 'Anguilla',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            186 => 
            array (
                'id' => 187,
                'code' => 662,
                'alpha2' => 'LC',
                'alpha3' => 'LCA',
                'nom_en_gb' => 'Saint Lucia',
                'nom' => 'Sainte-Lucie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            187 => 
            array (
                'id' => 188,
                'code' => 666,
                'alpha2' => 'PM',
                'alpha3' => 'SPM',
                'nom_en_gb' => 'Saint-Pierre and Miquelon',
                'nom' => 'Saint-Pierre-et-Miquelon',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            188 => 
            array (
                'id' => 189,
                'code' => 670,
                'alpha2' => 'VC',
                'alpha3' => 'VCT',
                'nom_en_gb' => 'Saint Vincent and the Grenadines',
                'nom' => 'Saint-Vincent-et-les Grenadines',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            189 => 
            array (
                'id' => 190,
                'code' => 674,
                'alpha2' => 'SM',
                'alpha3' => 'SMR',
                'nom_en_gb' => 'San Marino',
                'nom' => 'Saint-Marin',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            190 => 
            array (
                'id' => 191,
                'code' => 678,
                'alpha2' => 'ST',
                'alpha3' => 'STP',
                'nom_en_gb' => 'Sao Tome and Principe',
                'nom' => 'Sao Tomé-et-Principe',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            191 => 
            array (
                'id' => 192,
                'code' => 682,
                'alpha2' => 'SA',
                'alpha3' => 'SAU',
                'nom_en_gb' => 'Saudi Arabia',
                'nom' => 'Arabie Saoudite',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            192 => 
            array (
                'id' => 193,
                'code' => 686,
                'alpha2' => 'SN',
                'alpha3' => 'SEN',
                'nom_en_gb' => 'Senegal',
                'nom' => 'Sénégal',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            193 => 
            array (
                'id' => 194,
                'code' => 690,
                'alpha2' => 'SC',
                'alpha3' => 'SYC',
                'nom_en_gb' => 'Seychelles',
                'nom' => 'Seychelles',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            194 => 
            array (
                'id' => 195,
                'code' => 694,
                'alpha2' => 'SL',
                'alpha3' => 'SLE',
                'nom_en_gb' => 'Sierra Leone',
                'nom' => 'Sierra Leone',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            195 => 
            array (
                'id' => 196,
                'code' => 702,
                'alpha2' => 'SG',
                'alpha3' => 'SGP',
                'nom_en_gb' => 'Singapore',
                'nom' => 'Singapour',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            196 => 
            array (
                'id' => 197,
                'code' => 703,
                'alpha2' => 'SK',
                'alpha3' => 'SVK',
                'nom_en_gb' => 'Slovakia',
                'nom' => 'Slovaquie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            197 => 
            array (
                'id' => 198,
                'code' => 704,
                'alpha2' => 'VN',
                'alpha3' => 'VNM',
                'nom_en_gb' => 'Vietnam',
                'nom' => 'Viet Nam',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            198 => 
            array (
                'id' => 199,
                'code' => 705,
                'alpha2' => 'SI',
                'alpha3' => 'SVN',
                'nom_en_gb' => 'Slovenia',
                'nom' => 'Slovénie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            199 => 
            array (
                'id' => 200,
                'code' => 706,
                'alpha2' => 'SO',
                'alpha3' => 'SOM',
                'nom_en_gb' => 'Somalia',
                'nom' => 'Somalie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            200 => 
            array (
                'id' => 201,
                'code' => 710,
                'alpha2' => 'ZA',
                'alpha3' => 'ZAF',
                'nom_en_gb' => 'South Africa',
                'nom' => 'Afrique du Sud',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            201 => 
            array (
                'id' => 202,
                'code' => 716,
                'alpha2' => 'ZW',
                'alpha3' => 'ZWE',
                'nom_en_gb' => 'Zimbabwe',
                'nom' => 'Zimbabwe',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            202 => 
            array (
                'id' => 203,
                'code' => 724,
                'alpha2' => 'ES',
                'alpha3' => 'ESP',
                'nom_en_gb' => 'Spain',
                'nom' => 'Espagne',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            203 => 
            array (
                'id' => 204,
                'code' => 732,
                'alpha2' => 'EH',
                'alpha3' => 'ESH',
                'nom_en_gb' => 'Western Sahara',
                'nom' => 'Sahara Occidental',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            204 => 
            array (
                'id' => 205,
                'code' => 736,
                'alpha2' => 'SD',
                'alpha3' => 'SDN',
                'nom_en_gb' => 'Sudan',
                'nom' => 'Soudan',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            205 => 
            array (
                'id' => 206,
                'code' => 740,
                'alpha2' => 'SR',
                'alpha3' => 'SUR',
                'nom_en_gb' => 'Suriname',
                'nom' => 'Suriname',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            206 => 
            array (
                'id' => 207,
                'code' => 744,
                'alpha2' => 'SJ',
                'alpha3' => 'SJM',
                'nom_en_gb' => 'Svalbard and Jan Mayen',
                'nom' => 'Svalbard etÎle Jan Mayen',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            207 => 
            array (
                'id' => 208,
                'code' => 748,
                'alpha2' => 'SZ',
                'alpha3' => 'SWZ',
                'nom_en_gb' => 'Swaziland',
                'nom' => 'Swaziland',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            208 => 
            array (
                'id' => 209,
                'code' => 752,
                'alpha2' => 'SE',
                'alpha3' => 'SWE',
                'nom_en_gb' => 'Sweden',
                'nom' => 'Suède',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            209 => 
            array (
                'id' => 210,
                'code' => 756,
                'alpha2' => 'CH',
                'alpha3' => 'CHE',
                'nom_en_gb' => 'Switzerland',
                'nom' => 'Suisse',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            210 => 
            array (
                'id' => 211,
                'code' => 760,
                'alpha2' => 'SY',
                'alpha3' => 'SYR',
                'nom_en_gb' => 'Syrian Arab Republic',
                'nom' => 'République Arabe Syrienne',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            211 => 
            array (
                'id' => 212,
                'code' => 762,
                'alpha2' => 'TJ',
                'alpha3' => 'TJK',
                'nom_en_gb' => 'Tajikistan',
                'nom' => 'Tadjikistan',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            212 => 
            array (
                'id' => 213,
                'code' => 764,
                'alpha2' => 'TH',
                'alpha3' => 'THA',
                'nom_en_gb' => 'Thailand',
                'nom' => 'Thaïlande',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            213 => 
            array (
                'id' => 214,
                'code' => 768,
                'alpha2' => 'TG',
                'alpha3' => 'TGO',
                'nom_en_gb' => 'Togo',
                'nom' => 'Togo',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            214 => 
            array (
                'id' => 215,
                'code' => 772,
                'alpha2' => 'TK',
                'alpha3' => 'TKL',
                'nom_en_gb' => 'Tokelau',
                'nom' => 'Tokelau',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            215 => 
            array (
                'id' => 216,
                'code' => 776,
                'alpha2' => 'TO',
                'alpha3' => 'TON',
                'nom_en_gb' => 'Tonga',
                'nom' => 'Tonga',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            216 => 
            array (
                'id' => 217,
                'code' => 780,
                'alpha2' => 'TT',
                'alpha3' => 'TTO',
                'nom_en_gb' => 'Trinidad and Tobago',
                'nom' => 'Trinité-et-Tobago',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            217 => 
            array (
                'id' => 218,
                'code' => 784,
                'alpha2' => 'AE',
                'alpha3' => 'ARE',
                'nom_en_gb' => 'United Arab Emirates',
                'nom' => 'Émirats Arabes Unis',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            218 => 
            array (
                'id' => 219,
                'code' => 788,
                'alpha2' => 'TN',
                'alpha3' => 'TUN',
                'nom_en_gb' => 'Tunisia',
                'nom' => 'Tunisie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            219 => 
            array (
                'id' => 220,
                'code' => 792,
                'alpha2' => 'TR',
                'alpha3' => 'TUR',
                'nom_en_gb' => 'Turkey',
                'nom' => 'Turquie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            220 => 
            array (
                'id' => 221,
                'code' => 795,
                'alpha2' => 'TM',
                'alpha3' => 'TKM',
                'nom_en_gb' => 'Turkmenistan',
                'nom' => 'Turkménistan',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            221 => 
            array (
                'id' => 222,
                'code' => 796,
                'alpha2' => 'TC',
                'alpha3' => 'TCA',
                'nom_en_gb' => 'Turks and Caicos Islands',
                'nom' => 'Îles Turks et Caïques',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            222 => 
            array (
                'id' => 223,
                'code' => 798,
                'alpha2' => 'TV',
                'alpha3' => 'TUV',
                'nom_en_gb' => 'Tuvalu',
                'nom' => 'Tuvalu',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            223 => 
            array (
                'id' => 224,
                'code' => 800,
                'alpha2' => 'UG',
                'alpha3' => 'UGA',
                'nom_en_gb' => 'Uganda',
                'nom' => 'Ouganda',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            224 => 
            array (
                'id' => 225,
                'code' => 804,
                'alpha2' => 'UA',
                'alpha3' => 'UKR',
                'nom_en_gb' => 'Ukraine',
                'nom' => 'Ukraine',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            225 => 
            array (
                'id' => 226,
                'code' => 807,
                'alpha2' => 'MK',
                'alpha3' => 'MKD',
                'nom_en_gb' => 'The Former Yugoslav Republic of Macedonia',
                'nom' => 'L\'ex-République Yougoslave de Macédoine',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            226 => 
            array (
                'id' => 227,
                'code' => 818,
                'alpha2' => 'EG',
                'alpha3' => 'EGY',
                'nom_en_gb' => 'Egypt',
                'nom' => 'Égypte',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            227 => 
            array (
                'id' => 228,
                'code' => 826,
                'alpha2' => 'GB',
                'alpha3' => 'GBR',
                'nom_en_gb' => 'United Kingdom',
                'nom' => 'Royaume-Uni',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            228 => 
            array (
                'id' => 229,
                'code' => 833,
                'alpha2' => 'IM',
                'alpha3' => 'IMN',
                'nom_en_gb' => 'Isle of Man',
                'nom' => 'Île de Man',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            229 => 
            array (
                'id' => 230,
                'code' => 834,
                'alpha2' => 'TZ',
                'alpha3' => 'TZA',
                'nom_en_gb' => 'United Republic Of Tanzania',
                'nom' => 'République-Unie de Tanzanie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            230 => 
            array (
                'id' => 231,
                'code' => 840,
                'alpha2' => 'US',
                'alpha3' => 'USA',
                'nom_en_gb' => 'United States',
                'nom' => 'États-Unis',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            231 => 
            array (
                'id' => 232,
                'code' => 850,
                'alpha2' => 'VI',
                'alpha3' => 'VIR',
                'nom_en_gb' => 'U.S. Virgin Islands',
                'nom' => 'Îles Vierges des États-Unis',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            232 => 
            array (
                'id' => 233,
                'code' => 854,
                'alpha2' => 'BF',
                'alpha3' => 'BFA',
                'nom_en_gb' => 'Burkina Faso',
                'nom' => 'Burkina Faso',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            233 => 
            array (
                'id' => 234,
                'code' => 858,
                'alpha2' => 'UY',
                'alpha3' => 'URY',
                'nom_en_gb' => 'Uruguay',
                'nom' => 'Uruguay',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            234 => 
            array (
                'id' => 235,
                'code' => 860,
                'alpha2' => 'UZ',
                'alpha3' => 'UZB',
                'nom_en_gb' => 'Uzbekistan',
                'nom' => 'Ouzbékistan',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            235 => 
            array (
                'id' => 236,
                'code' => 862,
                'alpha2' => 'VE',
                'alpha3' => 'VEN',
                'nom_en_gb' => 'Venezuela',
                'nom' => 'Venezuela',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            236 => 
            array (
                'id' => 237,
                'code' => 876,
                'alpha2' => 'WF',
                'alpha3' => 'WLF',
                'nom_en_gb' => 'Wallis and Futuna',
                'nom' => 'Wallis et Futuna',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            237 => 
            array (
                'id' => 238,
                'code' => 882,
                'alpha2' => 'WS',
                'alpha3' => 'WSM',
                'nom_en_gb' => 'Samoa',
                'nom' => 'Samoa',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            238 => 
            array (
                'id' => 239,
                'code' => 887,
                'alpha2' => 'YE',
                'alpha3' => 'YEM',
                'nom_en_gb' => 'Yemen',
                'nom' => 'Yémen',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            239 => 
            array (
                'id' => 240,
                'code' => 891,
                'alpha2' => 'CS',
                'alpha3' => 'SCG',
                'nom_en_gb' => 'Serbia and Montenegro',
                'nom' => 'Serbie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            240 => 
            array (
                'id' => 241,
                'code' => 894,
                'alpha2' => 'ZM',
                'alpha3' => 'ZMB',
                'nom_en_gb' => 'Zambia',
                'nom' => 'Zambie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            241 => 
            array (
                'id' => 242,
                'code' => 0,
                'alpha2' => 'VT',
                'alpha3' => 'VTI',
                'nom_en_gb' => '',
                'nom' => 'Vatican',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            242 => 
            array (
                'id' => 243,
                'code' => 0,
                'alpha2' => '',
                'alpha3' => '',
                'nom_en_gb' => '',
                'nom' => 'Moldavie',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            243 => 
            array (
                'id' => 244,
                'code' => 0,
                'alpha2' => '',
                'alpha3' => '',
                'nom_en_gb' => '',
                'nom' => 'Monténégro',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            244 => 
            array (
                'id' => 245,
                'code' => 0,
                'alpha2' => '',
                'alpha3' => '',
                'nom_en_gb' => '',
                'nom' => 'Saint-Martin',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
            245 => 
            array (
                'id' => 246,
                'code' => 0,
                'alpha2' => '',
                'alpha3' => '',
                'nom_en_gb' => '',
                'nom' => 'Saint-Barthélémy',
                'defaut' => 0,
                'tva' => 0,
                'taux_tva' => '0.00',
            ),
        ));
        
        
    }
}