<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class DepartementsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('departements')->delete();

        DB::table('departements')->insert(array(
            0 =>
            array(
                'id' => 1,
                'departement' => 'Ain',
                'numero' => '01',
                'latitude' => '46.2475706',
                'longitude' => '5.1307681',
                'prefixe' => 'dans l\'',
                'nb_clubs' => 245,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            1 =>
            array(
                'id' => 2,
                'departement' => 'Aisne',
                'numero' => '02',
                'latitude' => '49.4769199',
                'longitude' => '3.4417368',
                'prefixe' => 'dans l\'',
                'nb_clubs' => 164,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            2 =>
            array(
                'id' => 3,
                'departement' => 'Allier',
                'numero' => '03',
                'latitude' => '46.3115552',
                'longitude' => '3.4167655',
                'prefixe' => 'dans l\'',
                'nb_clubs' => 104,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            3 =>
            array(
                'id' => 4,
                'departement' => 'Alpes-de-Haute-Provence',
                'numero' => '04',
                'latitude' => '44.0778716',
                'longitude' => '6.2375947',
                'prefixe' => 'en ',
                'nb_clubs' => 87,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            4 =>
            array(
                'id' => 5,
                'departement' => 'Hautes-Alpes',
                'numero' => '05',
                'latitude' => '44.6008723',
                'longitude' => '6.3226072',
                'prefixe' => 'en ',
                'nb_clubs' => 73,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            5 =>
            array(
                'id' => 6,
                'departement' => 'Alpes-Maritimes',
                'numero' => '06',
                'latitude' => '43.9466791',
                'longitude' => '7.179026',
                'prefixe' => 'en ',
                'nb_clubs' => 469,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            6 =>
            array(
                'id' => 7,
                'departement' => 'Ardèche',
                'numero' => '07',
                'latitude' => '44.759629',
                'longitude' => '4.5624426',
                'prefixe' => 'en ',
                'nb_clubs' => 109,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            7 =>
            array(
                'id' => 8,
                'departement' => 'Ardennes',
                'numero' => '08',
                'latitude' => '49.7624642',
                'longitude' => '4.6285053',
                'prefixe' => 'dans les ',
                'nb_clubs' => 73,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            8 =>
            array(
                'id' => 9,
                'departement' => 'Ariège',
                'numero' => '09',
                'latitude' => '42.9326292',
                'longitude' => '1.443469',
                'prefixe' => 'en ',
                'nb_clubs' => 75,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            9 =>
            array(
                'id' => 10,
                'departement' => 'Aube',
                'numero' => '10',
                'latitude' => '48.1563418',
                'longitude' => '4.3732462',
                'prefixe' => 'dans l\'',
                'nb_clubs' => 79,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            10 =>
            array(
                'id' => 11,
                'departement' => 'Aude',
                'numero' => '11',
                'latitude' => '43.0724667',
                'longitude' => '2.3813621',
                'prefixe' => 'dans l\'',
                'nb_clubs' => 158,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            11 =>
            array(
                'id' => 12,
                'departement' => 'Aveyron',
                'numero' => '12',
                'latitude' => '44.2179747',
                'longitude' => '2.6189273',
                'prefixe' => 'en ',
                'nb_clubs' => 197,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            12 =>
            array(
                'id' => 13,
                'departement' => 'Bouches-du-Rhône',
                'numero' => '13',
                'latitude' => '43.5911679',
                'longitude' => '5.3102505',
                'prefixe' => 'dans les ',
                'nb_clubs' => 769,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            13 =>
            array(
                'id' => 14,
                'departement' => 'Calvados',
                'numero' => '14',
                'latitude' => '49.1213315',
                'longitude' => '-0.4330578',
                'prefixe' => 'dans le',
                'nb_clubs' => 291,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            14 =>
            array(
                'id' => 15,
                'departement' => 'Cantal',
                'numero' => '15',
                'latitude' => '45.1191997',
                'longitude' => '2.6326062',
                'prefixe' => 'dans le',
                'nb_clubs' => 94,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            15 =>
            array(
                'id' => 16,
                'departement' => 'Charentes',
                'numero' => '16',
                'latitude' => '45.7519958',
                'longitude' => '0.1534761',
                'prefixe' => 'en ',
                'nb_clubs' => 183,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            16 =>
            array(
                'id' => 17,
                'departement' => 'Charente-Maritime',
                'numero' => '17',
                'latitude' => '45.74949',
                'longitude' => '-0.7733188',
                'prefixe' => 'en ',
                'nb_clubs' => 277,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            17 =>
            array(
                'id' => 18,
                'departement' => 'Cher',
                'numero' => '18',
                'latitude' => '46.954005',
                'longitude' => '2.4671908',
                'prefixe' => 'dans le ',
                'nb_clubs' => 117,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            18 =>
            array(
                'id' => 19,
                'departement' => 'Corrèze',
                'numero' => '19',
                'latitude' => '45.4320081',
                'longitude' => '2.0195909',
                'prefixe' => 'en ',
                'nb_clubs' => 133,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            19 =>
            array(
                'id' => 20,
                'departement' => 'Côte-d\'Or',
                'numero' => '21',
                'latitude' => '47.5126795',
                'longitude' => '4.635412',
                'prefixe' => 'en ',
                'nb_clubs' => 287,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            20 =>
            array(
                'id' => 21,
                'departement' => 'Côte-d\'Armor',
                'numero' => '22',
                'latitude' => '48.5108101',
                'longitude' => '-3.3263676',
                'prefixe' => 'en ',
                'nb_clubs' => 203,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            21 =>
            array(
                'id' => 22,
                'departement' => 'Creuse',
                'numero' => '23',
                'latitude' => '46.0377633',
                'longitude' => '2.0627832',
                'prefixe' => 'en ',
                'nb_clubs' => 56,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            22 =>
            array(
                'id' => 23,
                'departement' => 'Dordogne',
                'numero' => '24',
                'latitude' => '45.1469486',
                'longitude' => '0.7572205',
                'prefixe' => 'en ',
                'nb_clubs' => 128,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            23 =>
            array(
                'id' => 24,
                'departement' => 'Doubs',
                'numero' => '25',
                'latitude' => '47.0653896',
                'longitude' => '5.820028',
                'prefixe' => 'dans le ',
                'nb_clubs' => 243,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            24 =>
            array(
                'id' => 25,
                'departement' => 'Drôme',
                'numero' => '26',
                'latitude' => '44.7283646',
                'longitude' => '4.6782214',
                'prefixe' => 'dans la ',
                'nb_clubs' => 239,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            25 =>
            array(
                'id' => 26,
                'departement' => 'Eure',
                'numero' => '27',
                'latitude' => '49.1181763',
                'longitude' => '0.9582114',
                'prefixe' => 'dans l\'',
                'nb_clubs' => 219,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            26 =>
            array(
                'id' => 27,
                'departement' => 'Eure-et-Loir',
                'numero' => '28',
                'latitude' => '48.5525242',
                'longitude' => '1.1989814',
                'prefixe' => 'en ',
                'nb_clubs' => 142,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            27 =>
            array(
                'id' => 28,
                'departement' => 'Finistère',
                'numero' => '29',
                'latitude' => '48.2520249',
                'longitude' => '-3.9300525',
                'prefixe' => 'dans le ',
                'nb_clubs' => 322,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            28 =>
            array(
                'id' => 29,
                'departement' => 'Corse-du-Nord',
                'numero' => '20',
                'latitude' => '42.4097877',
                'longitude' => '9.2785583',
                'prefixe' => 'en ',
                'nb_clubs' => 87,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            29 =>
            array(
                'id' => 30,
                'departement' => 'Corse-du-Sud',
                'numero' => '20',
                'latitude' => '41.8102633',
                'longitude' => '8.9245343',
                'prefixe' => 'en ',
                'nb_clubs' => 87,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            30 =>
            array(
                'id' => 31,
                'departement' => 'Gard',
                'numero' => '30',
                'latitude' => '43.9446996',
                'longitude' => '4.1513764',
                'prefixe' => 'dans le ',
                'nb_clubs' => 288,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            31 =>
            array(
                'id' => 32,
                'departement' => 'Haute-Garonne',
                'numero' => '31',
                'latitude' => '43.4010462',
                'longitude' => '1.135302',
                'prefixe' => 'en ',
                'nb_clubs' => 566,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            32 =>
            array(
                'id' => 33,
                'departement' => 'Gers',
                'numero' => '32',
                'latitude' => '43.6940774',
                'longitude' => '-0.0999604',
                'prefixe' => 'dans le ',
                'nb_clubs' => 124,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            33 =>
            array(
                'id' => 34,
                'departement' => 'Gironde',
                'numero' => '33',
                'latitude' => '44.849665',
                'longitude' => '-0.4502368',
                'prefixe' => 'en ',
                'nb_clubs' => 585,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            34 =>
            array(
                'id' => 35,
                'departement' => 'Hérault',
                'numero' => '34',
                'latitude' => '43.5912356',
                'longitude' => '3.2583626',
                'prefixe' => 'dans l\'',
                'nb_clubs' => 495,
                'nb_profs' => 1,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            35 =>
            array(
                'id' => 36,
                'departement' => 'Ille-et-Vilaine',
                'numero' => '35',
                'latitude' => '48.2292016',
                'longitude' => '-1.5300695',
                'prefixe' => 'en ',
                'nb_clubs' => 448,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            36 =>
            array(
                'id' => 37,
                'departement' => 'Indre',
                'numero' => '36',
                'latitude' => '46.6613966',
                'longitude' => '1.4482662',
                'prefixe' => 'dans l\'',
                'nb_clubs' => 104,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            37 =>
            array(
                'id' => 38,
                'departement' => 'Indre-et-Loire',
                'numero' => '37',
                'latitude' => '47.2894925',
                'longitude' => '0.816097',
                'prefixe' => 'en ',
                'nb_clubs' => 261,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            38 =>
            array(
                'id' => 39,
                'departement' => 'Isère',
                'numero' => '38',
                'latitude' => '45.2882646',
                'longitude' => '4.9905205',
                'prefixe' => 'en ',
                'nb_clubs' => 442,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            39 =>
            array(
                'id' => 40,
                'departement' => 'Jura',
                'numero' => '39',
                'latitude' => '46.7819516',
                'longitude' => '5.1688258',
                'prefixe' => 'dans le ',
                'nb_clubs' => 106,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            40 =>
            array(
                'id' => 41,
                'departement' => 'Landes',
                'numero' => '40',
                'latitude' => '43.9412045',
                'longitude' => '-0.7532809',
                'prefixe' => 'dans les ',
                'nb_clubs' => 271,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            41 =>
            array(
                'id' => 42,
                'departement' => 'Loir-et-Cher',
                'numero' => '41',
                'latitude' => '47.6584485',
                'longitude' => '0.8537647',
                'prefixe' => 'en ',
                'nb_clubs' => 127,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            42 =>
            array(
                'id' => 43,
                'departement' => 'Loire',
                'numero' => '42',
                'latitude' => '46.32293',
                'longitude' => '1.0674249',
                'prefixe' => 'en ',
                'nb_clubs' => 361,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            43 =>
            array(
                'id' => 44,
                'departement' => 'Haute-Loire',
                'numero' => '43',
                'latitude' => '45.0844144',
                'longitude' => '3.2260765',
                'prefixe' => 'en ',
                'nb_clubs' => 73,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            44 =>
            array(
                'id' => 45,
                'departement' => 'Loire-Atlantique',
                'numero' => '44',
                'latitude' => '47.2780468',
                'longitude' => '-1.8157647',
                'prefixe' => 'en ',
                'nb_clubs' => 624,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            45 =>
            array(
                'id' => 46,
                'departement' => 'Loiret',
                'numero' => '45',
                'latitude' => '47.900771',
                'longitude' => '2.2018172',
                'prefixe' => 'dans le ',
                'nb_clubs' => 308,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            46 =>
            array(
                'id' => 47,
                'departement' => 'Lot',
                'numero' => '46',
                'latitude' => '44.9509263',
                'longitude' => '-116.1028528',
                'prefixe' => 'dans le ',
                'nb_clubs' => 91,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            47 =>
            array(
                'id' => 48,
                'departement' => 'Lot-et-Garonne',
                'numero' => '47',
                'latitude' => '44.2470173',
                'longitude' => '0.4502368',
                'prefixe' => 'en ',
                'nb_clubs' => 162,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            48 =>
            array(
                'id' => 49,
                'departement' => 'Lozère',
                'numero' => '48',
                'latitude' => '44.494203',
                'longitude' => '3.5812692',
                'prefixe' => 'en ',
                'nb_clubs' => 30,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            49 =>
            array(
                'id' => 50,
                'departement' => 'Maine-et-Loire',
                'numero' => '49',
                'latitude' => '47.3880648',
                'longitude' => '-1.120244',
                'prefixe' => 'dans le ',
                'nb_clubs' => 366,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            50 =>
            array(
                'id' => 51,
                'departement' => 'Manche',
                'numero' => '50',
                'latitude' => '49.114712',
                'longitude' => '-1.3115949',
                'prefixe' => 'dans la ',
                'nb_clubs' => 173,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            51 =>
            array(
                'id' => 52,
                'departement' => 'Marne',
                'numero' => '51',
                'latitude' => '48.9601822',
                'longitude' => '3.6573461',
                'prefixe' => 'en ',
                'nb_clubs' => 219,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            52 =>
            array(
                'id' => 53,
                'departement' => 'Haute-Marne',
                'numero' => '52',
                'latitude' => '48.1315818',
                'longitude' => '4.6984001',
                'prefixe' => 'en ',
                'nb_clubs' => 49,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            53 =>
            array(
                'id' => 54,
                'departement' => 'Mayenne',
                'numero' => '53',
                'latitude' => '48.3050874',
                'longitude' => '-0.6185636',
                'prefixe' => 'en ',
                'nb_clubs' => 154,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            54 =>
            array(
                'id' => 55,
                'departement' => 'Meurthe-et-Moselle',
                'numero' => '54',
                'latitude' => '48.7997007',
                'longitude' => '6.0947014',
                'prefixe' => 'en ',
                'nb_clubs' => 251,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            55 =>
            array(
                'id' => 56,
                'departement' => 'Meuse',
                'numero' => '55',
                'latitude' => '49.0824319',
                'longitude' => '5.2823997',
                'prefixe' => 'en ',
                'nb_clubs' => 62,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            56 =>
            array(
                'id' => 57,
                'departement' => 'Morbihan',
                'numero' => '56',
                'latitude' => '47.8852929',
                'longitude' => '-2.9001865',
                'prefixe' => 'dans le ',
                'nb_clubs' => 270,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            57 =>
            array(
                'id' => 58,
                'departement' => 'Moselle',
                'numero' => '57',
                'latitude' => '49.0195665',
                'longitude' => '6.2055318',
                'prefixe' => 'en ',
                'nb_clubs' => 406,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            58 =>
            array(
                'id' => 59,
                'departement' => 'Nièvre',
                'numero' => '58',
                'latitude' => '47.2381708',
                'longitude' => '3.5294522',
                'prefixe' => 'dans la ',
                'nb_clubs' => 82,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            59 =>
            array(
                'id' => 60,
                'departement' => 'Nord',
                'numero' => '59',
                'latitude' => '50.5276805',
                'longitude' => '2.6000717',
                'prefixe' => 'dans le ',
                'nb_clubs' => 782,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            60 =>
            array(
                'id' => 61,
                'departement' => 'Oise',
                'numero' => '60',
                'latitude' => '49.4214568',
                'longitude' => '2.4146396',
                'prefixe' => 'dans l\'',
                'nb_clubs' => 260,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            61 =>
            array(
                'id' => 62,
                'departement' => 'Orne',
                'numero' => '61',
                'latitude' => '48.6388567',
                'longitude' => '0.0848201',
                'prefixe' => 'dans l\'',
                'nb_clubs' => 101,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            62 =>
            array(
                'id' => 63,
                'departement' => 'Pas-de-Calais',
                'numero' => '62',
                'latitude' => '50.511922',
                'longitude' => '1.8114763',
                'prefixe' => 'dans le ',
                'nb_clubs' => 408,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            63 =>
            array(
                'id' => 64,
                'departement' => 'Puy-de-Dôme',
                'numero' => '63',
                'latitude' => '45.7124142',
                'longitude' => '3.0155825',
                'prefixe' => 'dans le ',
                'nb_clubs' => 254,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            64 =>
            array(
                'id' => 65,
                'departement' => 'Pyrénées-Atlantiques',
                'numero' => '64',
                'latitude' => '43.1857602',
                'longitude' => '-1.4416958',
                'prefixe' => 'en ',
                'nb_clubs' => 321,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            65 =>
            array(
                'id' => 66,
                'departement' => 'Hautes-Pyrénées',
                'numero' => '65',
                'latitude' => '43.1419523',
                'longitude' => '-0.4009574',
                'prefixe' => 'en ',
                'nb_clubs' => 96,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            66 =>
            array(
                'id' => 67,
                'departement' => 'Pyrénées-Orientales',
                'numero' => '66',
                'latitude' => '42.6012912',
                'longitude' => '2.539603',
                'prefixe' => 'en ',
                'nb_clubs' => 262,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            67 =>
            array(
                'id' => 68,
                'departement' => 'Bas-Rhin',
                'numero' => '67',
                'latitude' => '48.6343172',
                'longitude' => '7.5252938',
                'prefixe' => 'dans le ',
                'nb_clubs' => 381,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            68 =>
            array(
                'id' => 69,
                'departement' => 'Haut-Rhin',
                'numero' => '68',
                'latitude' => '47.9315041',
                'longitude' => '7.2441099',
                'prefixe' => 'dans le ',
                'nb_clubs' => 240,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            69 =>
            array(
                'id' => 70,
                'departement' => 'Rhône',
                'numero' => '69',
                'latitude' => '44.952398',
                'longitude' => '6.4840823',
                'prefixe' => 'dans le ',
                'nb_clubs' => 613,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            70 =>
            array(
                'id' => 71,
                'departement' => 'Haute-Saône',
                'numero' => '70',
                'latitude' => '47.7569806',
                'longitude' => '6.1556282',
                'prefixe' => 'en ',
                'nb_clubs' => 88,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            71 =>
            array(
                'id' => 72,
                'departement' => 'Saône-et-Loire',
                'numero' => '71',
                'latitude' => '46.6545528',
                'longitude' => '3.9835139',
                'prefixe' => 'en ',
                'nb_clubs' => 170,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            72 =>
            array(
                'id' => 73,
                'departement' => 'Sarthe',
                'numero' => '72',
                'latitude' => '47.9217014',
                'longitude' => '0.1655803',
                'prefixe' => 'dans la ',
                'nb_clubs' => 256,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            73 =>
            array(
                'id' => 74,
                'departement' => 'Savoie',
                'numero' => '73',
                'latitude' => '45.4937427',
                'longitude' => '5.8433037',
                'prefixe' => 'en ',
                'nb_clubs' => 162,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            74 =>
            array(
                'id' => 75,
                'departement' => 'Haute-Savoie',
                'numero' => '74',
                'latitude' => '46.1756788',
                'longitude' => '6.5389621',
                'prefixe' => 'en ',
                'nb_clubs' => 235,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            75 =>
            array(
                'id' => 76,
                'departement' => 'Paris',
                'numero' => '75',
                'latitude' => '48.856614',
                'longitude' => '2.3522219',
                'prefixe' => 'à ',
                'nb_clubs' => 665,
                'nb_profs' => 2,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            76 =>
            array(
                'id' => 77,
                'departement' => 'Seine-Maritime',
                'numero' => '76',
                'latitude' => '49.6054187',
                'longitude' => '0.9748439',
                'prefixe' => 'en ',
                'nb_clubs' => 473,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            77 =>
            array(
                'id' => 78,
                'departement' => 'Seine-et-Marne',
                'numero' => '77',
                'latitude' => '48.841082',
                'longitude' => '2.999366',
                'prefixe' => 'en ',
                'nb_clubs' => 436,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            78 =>
            array(
                'id' => 79,
                'departement' => 'Yvelines',
                'numero' => '78',
                'latitude' => '48.7850939',
                'longitude' => '1.8256572',
                'prefixe' => 'dans les ',
                'nb_clubs' => 433,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            79 =>
            array(
                'id' => 80,
                'departement' => 'Deux-Sèvres',
                'numero' => '79',
                'latitude' => '46.5926541',
                'longitude' => '-0.3962844',
                'prefixe' => 'dans les ',
                'nb_clubs' => 143,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            80 =>
            array(
                'id' => 81,
                'departement' => 'Somme',
                'numero' => '80',
                'latitude' => '49.914518',
                'longitude' => '2.2707095',
                'prefixe' => 'dans la ',
                'nb_clubs' => 226,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            81 =>
            array(
                'id' => 82,
                'departement' => 'Tarn',
                'numero' => '81',
                'latitude' => '43.7905182',
                'longitude' => '1.6759009',
                'prefixe' => 'dans le ',
                'nb_clubs' => 195,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            82 =>
            array(
                'id' => 83,
                'departement' => 'Tarn-et-Garonne',
                'numero' => '82',
                'latitude' => '44.0126679',
                'longitude' => '1.2891036',
                'prefixe' => 'dans le ',
                'nb_clubs' => 105,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            83 =>
            array(
                'id' => 84,
                'departement' => 'Var',
                'numero' => '83',
                'latitude' => '43.467646',
                'longitude' => '6.2375947',
                'prefixe' => 'dans le ',
                'nb_clubs' => 407,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            84 =>
            array(
                'id' => 85,
                'departement' => 'Vaucluse',
                'numero' => '84',
                'latitude' => '44.0437722',
                'longitude' => '4.6427741',
                'prefixe' => 'dans le ',
                'nb_clubs' => 221,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            85 =>
            array(
                'id' => 86,
                'departement' => 'Vendée',
                'numero' => '85',
                'latitude' => '46.6613966',
                'longitude' => '-1.4482662',
                'prefixe' => 'en ',
                'nb_clubs' => 300,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            86 =>
            array(
                'id' => 87,
                'departement' => 'Vienne',
                'numero' => '86',
                'latitude' => '46.6107612',
                'longitude' => '-0.0063252',
                'prefixe' => 'dans la ',
                'nb_clubs' => 199,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            87 =>
            array(
                'id' => 88,
                'departement' => 'Haute-Vienne',
                'numero' => '87',
                'latitude' => '45.7435173',
                'longitude' => '1.4025484',
                'prefixe' => 'en ',
                'nb_clubs' => 192,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            88 =>
            array(
                'id' => 89,
                'departement' => 'Vosges',
                'numero' => '88',
                'latitude' => '48.1446427',
                'longitude' => '6.3355935',
                'prefixe' => 'dans les ',
                'nb_clubs' => 89,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            89 =>
            array(
                'id' => 90,
                'departement' => 'Yonne',
                'numero' => '89',
                'latitude' => '47.8538484',
                'longitude' => '3.0339404',
                'prefixe' => 'dans l\'',
                'nb_clubs' => 143,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            90 =>
            array(
                'id' => 91,
                'departement' => 'Territoire-de-Belfort',
                'numero' => '90',
                'latitude' => '47.5946573',
                'longitude' => '6.9207716',
                'prefixe' => 'dans le ',
                'nb_clubs' => 41,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            91 =>
            array(
                'id' => 92,
                'departement' => 'Essonne',
                'numero' => '91',
                'latitude' => '48.4585698',
                'longitude' => '2.1569416',
                'prefixe' => 'en ',
                'nb_clubs' => 436,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            92 =>
            array(
                'id' => 93,
                'departement' => 'Hauts-de-Seine',
                'numero' => '92',
                'latitude' => '48.8400716',
                'longitude' => '2.1012381',
                'prefixe' => 'en ',
                'nb_clubs' => 369,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            93 =>
            array(
                'id' => 94,
                'departement' => 'Seine-Saint-Denis',
                'numero' => '93',
                'latitude' => '48.9097039',
                'longitude' => '2.3057181',
                'prefixe' => 'en ',
                'nb_clubs' => 267,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            94 =>
            array(
                'id' => 95,
                'departement' => 'Val-de-Marne',
                'numero' => '94',
                'latitude' => '48.7931426',
                'longitude' => '2.4740337',
                'prefixe' => 'dans le ',
                'nb_clubs' => 265,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            95 =>
            array(
                'id' => 96,
                'departement' => 'Val-d\'Oise',
                'numero' => '95',
                'latitude' => '49.0747504',
                'longitude' => '1.8216746',
                'prefixe' => 'dans le ',
                'nb_clubs' => 305,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            96 =>
            array(
                'id' => 97,
                'departement' => 'Guadeloupe',
                'numero' => '971',
                'latitude' => '16.265',
                'longitude' => '-61.551',
                'prefixe' => 'en ',
                'nb_clubs' => 16,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            97 =>
            array(
                'id' => 98,
                'departement' => 'Martinique',
                'numero' => '972',
                'latitude' => '14.641528',
                'longitude' => '-61.024174',
                'prefixe' => 'en ',
                'nb_clubs' => 43,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            98 =>
            array(
                'id' => 99,
                'departement' => 'Guyane',
                'numero' => '973',
                'latitude' => '3.933889',
                'longitude' => '-53.125782',
                'prefixe' => 'en ',
                'nb_clubs' => 5,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            99 =>
            array(
                'id' => 100,
                'departement' => 'Réunion',
                'numero' => '974',
                'latitude' => '-21.115141',
                'longitude' => '55.536384',
                'prefixe' => 'à la ',
                'nb_clubs' => 71,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            100 =>
            array(
                'id' => 101,
                'departement' => 'Saint-Pierre-et-Miquelon',
                'numero' => '975',
                'latitude' => '46.9577083',
                'longitude' => '-56.5330829',
                'prefixe' => 'à ',
                'nb_clubs' => 3,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
            101 =>
            array(
                'id' => 102,
                'departement' => 'Mayotte',
                'numero' => '976',
                'latitude' => '-12.8275',
                'longitude' => '45.166244',
                'prefixe' => 'à ',
                'nb_clubs' => 1,
                'nb_profs' => 0,
                'nb_lieux' => 0,
                'nb_events' => 0,
            ),
        ));
    }
}
