const defaultTheme = require("tailwindcss/defaultTheme");

/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php",
        "./storage/framework/views/*.php",
        "./resources/views/**/*.blade.php",
        "./resources/js/**/*.vue",
        "./resources/js/**/*.js",
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ["Figtree", ...defaultTheme.fontFamily.sans],
            },
            colors: {
                darkblue: "#151f32",
                midnight: "#121b4f",
                gold: "#ffd700",
            },
            zIndex: {
                45: "45",
                60: "60",
                100: "100",
            },
            backgroundImage: {
                "la-base": "url('/images/0-min.jpg')",
                "discipline-1": "url('/images/disciplines/1-min.jpg')",
                "discipline-3": "url('/images/disciplines/3-min.jpg')",
                "discipline-5": "url('/images/disciplines/5-min.jpg')",
                "discipline-7": "url('/images/disciplines/7-min.jpg')",
                "discipline-8": "url('/images/disciplines/8-min.jpg')",
                "discipline-14": "url('/images/disciplines/14-min.jpg')",
                "discipline-23": "url('/images/disciplines/23-min.jpg')",
                "discipline-29": "url('/images/disciplines/29-min.jpg')",
                "discipline-30": "url('/images/disciplines/30-min.jpg')",
                "discipline-32": "url('/images/disciplines/32-min.jpg')",
                "discipline-35": "url('/images/disciplines/35-min.jpg')",
                "discipline-49": "url('/images/disciplines/49-min.jpg')",
                "discipline-53": "url('/images/disciplines/53-min.jpg')",
                "discipline-58": "url('/images/disciplines/58-min.jpg')",
                "discipline-61": "url('/images/disciplines/61-min.jpg')",
                "discipline-63": "url('/images/disciplines/63-min.jpg')",
                "discipline-68": "url('/images/disciplines/68-min.jpg')",
                "discipline-72": "url('/images/disciplines/72-min.jpg')",
                "discipline-73": "url('/images/disciplines/73-min.jpg')",
                "discipline-83": "url('/images/disciplines/83-min.jpg')",
                "discipline-88": "url('/images/disciplines/88-min.jpg')",
                "discipline-106": "url('/images/disciplines/106-min.jpg')",
                "discipline-129": "url('/images/disciplines/129-min.jpg')",
                "discipline-131": "url('/images/disciplines/131-min.jpg')",
                "discipline-145": "url('/images/disciplines/145-min.jpg')",
                "discipline-167": "url('/images/disciplines/167-min.jpg')",
                "discipline-170": "url('/images/disciplines/170-min.jpg')",
                "discipline-176": "url('/images/disciplines/176-min.jpg')",
                "discipline-181": "url('/images/disciplines/181-min.jpg')",
                "discipline-189": "url('/images/disciplines/189-min.jpg')",
                "discipline-204": "url('/images/disciplines/204-min.jpg')",
                "discipline-206": "url('/images/disciplines/206-min.jpg')",
                "discipline-212": "url('/images/disciplines/212-min.jpg')",
                "discipline-214": "url('/images/disciplines/214-min.jpg')",
                "discipline-220": "url('/images/disciplines/220-min.jpg')",
                "discipline-221": "url('/images/disciplines/221-min.jpg')",
                "discipline-222": "url('/images/disciplines/222-min.jpg')",
                "discipline-223": "url('/images/disciplines/223-min.jpg')",
                "discipline-224": "url('/images/disciplines/224-min.jpg')",
                "discipline-229": "url('/images/disciplines/229-min.jpg')",
                "discipline-232": "url('/images/disciplines/232-min.jpg')",
                "discipline-233": "url('/images/disciplines/233-min.jpg')",
                "discipline-238": "url('/images/disciplines/238-min.jpg')",
                "discipline-240": "url('/images/disciplines/240-min.jpg')",
                "discipline-241": "url('/images/disciplines/241-min.jpg')",
                "discipline-243": "url('/images/disciplines/243-min.jpg')",
                "discipline-244": "url('/images/disciplines/244-min.jpg')",
                "discipline-246": "url('/images/disciplines/246-min.jpg')",
                "discipline-247": "url('/images/disciplines/247-min.jpg')",
                "discipline-248": "url('/images/disciplines/248-min.jpg')",
                "discipline-249": "url('/images/disciplines/249-min.jpg')",
                "discipline-250": "url('/images/disciplines/250-min.jpg')",
                "discipline-251": "url('/images/disciplines/251-min.jpg')",
                "discipline-254": "url('/images/disciplines/254-min.jpg')",
                "discipline-259": "url('/images/disciplines/259-min.jpg')",
                "discipline-262": "url('/images/disciplines/262-min.jpg')",
                "discipline-263": "url('/images/disciplines/263-min.jpg')",
                "discipline-265": "url('/images/disciplines/265-min.jpg')",
                "discipline-270": "url('/images/disciplines/270-min.jpg')",
                "discipline-271": "url('/images/disciplines/271-min.jpg')",
                "discipline-276": "url('/images/disciplines/276-min.jpg')",
                "discipline-279": "url('/images/disciplines/279-min.jpg')",
                "discipline-280": "url('/images/disciplines/280-min.jpg')",
                "discipline-286": "url('/images/disciplines/286-min.jpg')",
                "discipline-288": "url('/images/disciplines/288-min.jpg')",
                "discipline-289": "url('/images/disciplines/289-min.jpg')",
                "discipline-293": "url('/images/disciplines/293-min.jpg')",
                "discipline-294": "url('/images/disciplines/294-min.jpg')",
                "discipline-295": "url('/images/disciplines/295-min.jpg')",
                "discipline-296": "url('/images/disciplines/296-min.jpg')",
                "discipline-298": "url('/images/disciplines/298-min.jpg')",
                "discipline-302": "url('/images/disciplines/302-min.jpg')",
                "discipline-305": "url('/images/disciplines/305-min.jpg')",
                "discipline-306": "url('/images/disciplines/306-min.jpg')",
                "discipline-307": "url('/images/disciplines/307-min.jpg')",
                "discipline-308": "url('/images/disciplines/308-min.jpg')",
                "discipline-309": "url('/images/disciplines/309-min.jpg')",
                "discipline-310": "url('/images/disciplines/310-min.jpg')",
                "discipline-311": "url('/images/disciplines/311-min.jpg')",
                "discipline-312": "url('/images/disciplines/312-min.jpg')",
                "discipline-313": "url('/images/disciplines/313-min.jpg')",
                "discipline-315": "url('/images/disciplines/315-min.jpg')",
                "discipline-316": "url('/images/disciplines/316-min.jpg')",
                "discipline-319": "url('/images/disciplines/319-min.jpg')",
                "discipline-320": "url('/images/disciplines/320-min.jpg')",
                "discipline-321": "url('/images/disciplines/321-min.jpg')",
                "discipline-328": "url('/images/disciplines/328-min.jpg')",
            },
        },
    },

    plugins: [
        require("@tailwindcss/forms"),
        require("prettier-plugin-tailwindcss"),
    ],
};
